### ISSUE TITLE
Crash on extraction of non-zip file

### ISSUE THREAD

**Issue by sirateek** [ta-assistant/TA-CLI#44]
## Step to reproduce
1. `ta init --workid testWork`
2. TA-CLI ask for the vscode and file extraction
3. The crash happen on extraction of files `.DS_Store` and the broken zip file I created for testing purposes.

## Environment
OS: Mac OS 11.4
Python: 3.8

## Log:
```
❯ ta start
Do you want to open vscode?(y/n): y
Folder by folder?(y/n): y
/Users/sirateek/ProjectRepository/Python/TestDir/ta/work.json doesn't exits
/Users/sirateek/ProjectRepository/Python/TestDir/ta/work.json created
Sucessfully add draft
Your workId is {'prefix': 'https://ta-api.sirateek.dev/', 'workID': 'testWork', 'apikeydir': '/Users/sirateek/key'}
Traceback (most recent call last):---| 16.7% .DS_Store complete
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ta", line 33, in <module>
    sys.exit(load_entry_point('ta', 'console_scripts', 'ta')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sirateek/ProjectRepository/Python/TA-CLI/ta_cli/cli.py", line 62, in start
    run_work(current_dir, openvs, fbf)
  File "/Users/sirateek/ProjectRepository/Python/TA-CLI/src/main/run_work.py", line 34, in run_work
    unzipfile(path)
  File "/Users/sirateek/ProjectRepository/Python/TA-CLI/lib/file_management/extract.py", line 32, in unzipfile
    with zipfile.ZipFile(name) as my_zip:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by vitvara** [comment]
handled
